kraken2:
    db: ~/mirror/kraken2/k2_pluspf_20230605
    job_threads: 6
    job_mem: 10G
    options: ''

bracken:
    db: ~/mirror/kraken2/k2_pluspf_20230605
    taxdump: ~/mirror/ncbi_taxonomy/taxdump_20230706
    read_len: 250
    job_threads: 6
    job_mem: 10G
    options: ''

report:

    # prefix to use for publishing the report from this pipeline
    prefix: default

