humann3:

    # database settings
    db_metaphlan_path: /path/to/metaphlan/database/directory
    db_metaphlan_id: mpa_v31_CHOCOPhlAn_201901
    db_nucleotide: /path/to/chocophlan/database/directory 
    db_protein: /path/to/uniref/database/directory

    # additional humann3 options
    options: ""
    
    # job options
    job_mem: 40G
    job_threads: 4

report:
    # prefix to use for publishing the report from this pipeline
    prefix: default