humann3:
    # database settings
    db_nucleotide: /path/to/chocophlan/database/directory 
    db_protein: /path/to/uniref/database/directory
    
    nthreads: 1

    # additional humann3 options
    options: pipelines/pipeline_preprocess.py

    memory: 40
    threads: 4

    run_options:

report:
    # prefix to use for publishing the report from this pipeline
    prefix: default