kraken2:
    db: ~/mirror/kraken2/kraken2-microbial-fatfree
    job_threads: 6
    job_mem: 10G
    options: ''

bracken:
    db: ~/mirror/kraken2/kraken2-microbial-fatfree
    job_threads: 6
    job_mem: 10G
    options: ''

report:

    # prefix to use for publishing the report from this pipeline
    prefix: default

