kraken2:
    db: /gfs/mirror/kraken2/kraken2-microbial-fatfree
    nthreads: 6
    job_mem: 10
    options: ''
    run_options: ''
    
braken:
    db:
    kreport:
    read_len:
    classification_level:

report:

    # prefix to use for publishing the report from this pipeline
    prefix: default

