general:
# directory where reads are located, specified as:
# "0" for the current directory "."
# "1" for the subdirectory "./data.dir".
# alternatively, a path may be specified, but this is not recommended.
input: 1  

preprocess:
  pool_input_regex: ".+_(chow|hfd|[^_]+)_(WT|KO)\\.fastq\\.1\\.gz"
  pool_output_regex: "\\1_\\2_pooled.fastq.1.gz"

pool:
  enable: true  # Set to true to enable pooling before assembly
  job_threads: 4  # Example configuration for resources
  job_memory: '16G'  # Example configuration for memory
  options: ''  # Additional options, if any

read_error_correction:
  enable: true  # or false, depending on whether you want to enable or disable it

spades:
  options: '--threads 8 --memory 8' 
  # job_threads: 8  # Number of CPU threads for SPAdes
  #job_memory: '8'  # Memory allocation for SPAdes (in GB)
  error_correction_run_options: # Add specific options for error correction here
  error_correction_options: ''
  run_options: '--meta'   # Example option for SPAdes meta mode (you can modify this)

