humann3:

    # database settings
    db_metaphlan_path: /well/kir/mirror/metaphlan3/metaphlan_databases_3.1
    db_metaphlan_id: mpa_v31_CHOCOPhlAn_201901
    db_nucleotide: /well/kir/mirror/humann3/chocophlan 
    db_protein: /well/kir/mirror/humann3/uniref/uniref90

    # additional humann3 options
    options: ""
    
    # job options
    job_memory: 40G
    job_threads: 4

merge:
    # job options of tasks that merge humann3 outputs
    job_memory: 8G
    job_threads: 1

report:
    # prefix to use for publishing the report from this pipeline
    prefix: default